#pragma once

#include "NativeGameplayTags.h"

namespace GYGameplayTags
{
	/* Consumable Items */
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Consumable)

	/* 인첸트 온히트 효과 발동 쿨타임 (효과별 독립) */
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Bleed)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_DefBreak)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Lifesteal)

	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy)

	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Knight_GreatSword_Attack01)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Knight_GreatSword_Attack02)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Knight_GreatSword_Attack03)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Knight_GreatSword_Attack04)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Knight_GreatSword_Attack05)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Knight_GreatSword_Attack06)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Knight_GreatSword_Attack07)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Knight_GreatSword_Attack08)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Knight_GreatSword_Attack09)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Knight_GreatSword_Attack10)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Knight_GreatSword_Attack11)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Knight_GreatSword_Attack12)

	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Knight_LongSword_Attack01)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Knight_LongSword_Attack02)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Knight_LongSword_Attack03)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Knight_LongSword_Attack04)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Knight_LongSword_Attack05)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Knight_LongSword_Ultimate)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Knight_LongSword_RunAttack)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Knight_LongSword_JustGuardAttack)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Knight_LongSword_Dodge)

	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_FengMao_ComboAttack01)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_FengMao_ComboAttack02)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_FengMao_ComboAttack03)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_FengMao_ComboAttack04)

	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Sparrow_Attack01)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Sparrow_Attack02)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Sparrow_Attack03)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_Sparrow_Attack04)

	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_NormalFlower_Attack01)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_NormalFlower_Attack02)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_NormalFlower_Attack03)

	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_IggyScorch_Attack01)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_IggyScorch_Attack02)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_IggyScorch_Attack03)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_IggyScorch_Attack04)

	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_PlantRoot_Attack01)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_PlantRoot_Attack02)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Enemy_PlantRoot_Attack03)

}
