#pragma once

#include "NativeGameplayTags.h"

namespace GYGameplayTags
{
	// Item events
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Item_Equipped)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Item_Unequipped)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Item_Enhanced)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Item_Enchanted)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Item_GemSocketed)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Item_Used)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Item_Used_HP)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Item_Used_SP)

	// Inventory events
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Inventory_ItemAdded)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Inventory_ItemRemoved)

	// Attack events
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Anim_Attack_DoTrace)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Anim_ComboWindowOpen)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Anim_ComboWindowClose)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Anim_TagApplyStart)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Input_Attack)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Input_AttackRelease)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combo_StepStart)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combo_Advance)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Input_ParryRelease)

	//Parkour Dodge Events

	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_Parkour_Execute)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_Dodge_Execute)

	// Parry events
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Parry_Hit)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Parried)

	// JustGuard events
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_JustGuard_Hit)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_JustGuarded)

	// Block events
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Block_Hit)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Block_LoopEnd)

	// Enemy Attack events
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Enemy_WeaponTrace_Hit)
	// 트레이스 윈도우(스윙) 시작 — 어빌리티가 HitDamageWeights 인덱스를 스윙 기준으로 맞추는 데 사용
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Enemy_WeaponTrace_Begin)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Enemy_LaunchProjectile)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Enemy_Slam_Land)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Enemy_Teleport_Trigger)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Enemy_SpawnAreaDenialZones)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Enemy_FireBreath_Tick)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Enemy_FireBreath_Start)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Enemy_FireBreath_End)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Enemy_Combo_Branch)

	//TimeRift
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_TimeRift_Rest)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_TimeRift_Exit)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_TimeRift_Altar)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_TimeRift_Altar_Exit)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_TimeRift_Enchant)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_TimeRift_Enchant_Exit)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_TimeRift_SkillTree)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_TimeRift_SkillTree_Exit)

	//Ladder
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ladder_ClimbRequest)

	//SkillTree
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_SkillTree_Unlock)

	// Disable events
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Hit_Stagger)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Hit_Stun)

}
