#pragma once

#include "NativeGameplayTags.h"

namespace GYGameplayTags
{
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Open_LootBox)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Open_Door)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_TimeRift_Sit)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Ending_Start)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Ladder_Activate)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Boss_Intro)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Boss_Outro)
}
