#pragma once

#include "NativeGameplayTags.h"

namespace GYGameplayTags
{
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Region)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Region_Test)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Region_Town)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Region_Forest)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Region_Boss_Local1)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Region_Boss_Final)
}
