#pragma once

#include "NativeGameplayTags.h"

namespace GYGameplayTags
{
	/* 플레이어 사운드 */
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Player_Walk)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Player_Run)

	// 약공격
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Player_Attack_Light);
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Player_Attack_Stab);

	// 강공격
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Player_Attack_Heavy_Charge);
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Player_Attack_Heavy_Release);

	// 패링
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Player_Parry_Attempt);
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Player_Parry_Success);

	// 방패 블로킹
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Player_Block_Success);
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Player_Block_Break);

	// 회피
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Player_Dodge);

	// 물약
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Player_Potion);
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Player_Healing);

	// 공격 적중
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Player_Hit_Light);
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Player_Hit_Heavy);
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Player_Hit_Critical);
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Player_Hit_ParryCounter);

	// 플레이어 피격
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Player_Damage_Light);
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Player_Damage_Heavy);

	// 피격 리액션
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Player_Stagger);
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Player_Stun);

	/* 적 사운드 */
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Enemy_Regen)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Feng_Attack_1)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Feng_Attack_2)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Feng_Attack_3)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Feng_Attack_4)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Feng_Jump_Up)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Feng_Death)

	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Sparrow_Attack)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Sparrow_Death)

	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Boss_Impact)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Boss_Seed)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Boss_Poison)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Boss_Bloom)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Boss_Roar)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Boss_Vine)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Boss_Pawn_Death)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Boss_Pawn_Attack)

	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_ChapterBoss_GreatSword_1)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_ChapterBoss_GreatSword_2)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_ChapterBoss_GreatSword_3)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_ChapterBoss_GreatSword_4)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_ChapterBoss_GreatSword_5)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_ChapterBoss_Sword_1)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_ChapterBoss_Sword_2)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_ChapterBoss_Sword_3)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_ChapterBoss_Sword_4)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_ChapterBoss_Blade)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_ChapterBoss_LongDash)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_ChapterBoss_Dash)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_ChapterBoss_Death)

	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Morigesh_ElectricMark)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Morigesh_Lightning)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Morigesh_Orb)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Morigesh_Knife)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Morigesh_Ultimate)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Morigesh_Death)

	// 스코치 Scorch
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Scorch_Run)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Scorch_Eat)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Scorch_Jump)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Scorch_Bomb)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Scorch_Pop)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Scorch_Fire)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Scorch_Death)

	// 그래이스톤
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_GreyStone_Death)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_GreyStone_Attack_1)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_GreyStone_Attack_2)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_GreyStone_Dash)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_GreyStone_Voice)

	/* 상호 작용*/
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Interaction_LootBox_Close)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Interaction_LootBox_Open)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Interaction_LootBox_First)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Interaction_Door_Open)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Interaction_Door_Close)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Interaction_TimeRift)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Interaction_TimeRift_Rest)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Interaction_TimeRift_Enchant)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Interaction_TimeRift_Altar)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Interaction_SecretDiary)

	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Quest_Completed)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_World_Reset)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_World_Clock)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Item_Looting)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Level_Up)

	/* 환경 */
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Ambient_Machine)

	/* BGM */
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_BGM_Combat)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_BGM_Lobby)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_BGM_Area1)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_BGM_Area2)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_BGM_FinalBoss)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_BGM_RegionBoss)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_BGM_Village)

	/* Voice */
}
