#pragma once

#include "NativeGameplayTags.h"

namespace GYStateTags
{
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Life_Alive)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Life_Downed)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Life_BeingRevived)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Life_Dead)

	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Hit_Stagger)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Hit_KnockDown)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Hit_Stun)

	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_InCombat)
	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_SuperArmor)

	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Reviving)

	GY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Interaction_TimeRift)

}
