# ============================================================
# GY local Supabase backend setup (Windows / PowerShell)
#   Run: double-click db-setup.bat
#        (or: powershell -ExecutionPolicy Bypass -File supabase\db-setup.ps1)
#   Steps: check Docker -> download supabase CLI -> init (first run) -> start -> db reset
#   See README.md (Korean) for details.
# ============================================================

$ErrorActionPreference = "Stop"
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

# Repo root = parent of this script's folder (supabase/)
$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
Set-Location $RepoRoot

$BinDir = Join-Path $PSScriptRoot ".bin"
$Sb     = Join-Path $BinDir "supabase.exe"

# 1) Docker (manual install; reboot involved so not scripted)
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Write-Host "[setup] Docker Desktop not found. Install it first, then re-run:" -ForegroundColor Red
    Write-Host "        https://www.docker.com/products/docker-desktop/  (use WSL2, reboot required)" -ForegroundColor Red
    exit 1
}
docker info *> $null
if ($LASTEXITCODE -ne 0) {
    Write-Host "[setup] Start Docker Desktop (tray whale icon must be green), then re-run." -ForegroundColor Red
    exit 1
}

# 2) supabase CLI binary (download if missing; no Node/scoop/npm)
if (-not (Test-Path $Sb)) {
    Write-Host "[setup] Downloading supabase CLI..." -ForegroundColor Yellow
    New-Item -ItemType Directory -Force -Path $BinDir | Out-Null
    $rel = Invoke-RestMethod "https://api.github.com/repos/supabase/cli/releases/latest" `
        -Headers @{ "User-Agent" = "gy-setup"; "Accept" = "application/vnd.github+json" }
    $asset = $rel.assets | Where-Object { $_.name -match "windows.*amd64.*\.zip$" } | Select-Object -First 1
    if (-not $asset) { throw "supabase windows zip asset not found (manual install needed)" }
    $zip = Join-Path $env:TEMP "supabase_cli.zip"
    Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $zip
    Expand-Archive -Path $zip -DestinationPath $BinDir -Force
    Remove-Item $zip
    Write-Host "[setup] supabase CLI installed ($($rel.tag_name))" -ForegroundColor Green
}

# 3) config.toml is committed, so normally skipped.
#    Fallback only (if missing): init non-interactively so no y/N prompts appear.
if (-not (Test-Path (Join-Path $RepoRoot "supabase\config.toml"))) {
    Write-Host "[setup] config.toml missing - running supabase init (fallback)..." -ForegroundColor Yellow
    & $Sb init --force --with-vscode-settings=false --with-intellij-settings=false 2>$null
    if ($LASTEXITCODE -ne 0) { & $Sb init }  # fallback for older CLI that lacks those flags
}

# 4) start local stack + apply migrations/seed
Write-Host "[setup] supabase start (first run pulls images, a few minutes)..." -ForegroundColor Yellow
& $Sb start
Write-Host "[setup] supabase db reset (migrations + seed)..." -ForegroundColor Yellow
& $Sb db reset

# 5) generate Config\DefaultGYPersistence.ini from local supabase status
#    (key is NOT committed; each dev's local key is written here, file is gitignored)
Write-Host "[setup] writing Config\DefaultGYPersistence.ini (local URL + secret key)..." -ForegroundColor Yellow
$envOut  = (& $Sb status -o env) | Out-String
$apiUrl  = ([regex]::Match($envOut, 'API_URL="?([^"\r\n]+)"?')).Groups[1].Value
$secret  = ([regex]::Match($envOut, 'SECRET_KEY="?([^"\r\n]+)"?')).Groups[1].Value
if ($apiUrl -and $secret) {
    $iniText = "[/Script/GY.GYPersistenceSettings]`r`n" +
               "; Local only (auto-generated by db-setup, gitignored). Do NOT put hosted values here - inject via CI/env.`r`n" +
               "ServerBaseUrl=`"$apiUrl`"`r`n" +
               "SecretKey=$secret`r`n"
    Set-Content -Path (Join-Path $RepoRoot "Config\DefaultGYPersistence.ini") -Value $iniText -Encoding ascii
    Write-Host "[setup] ini written." -ForegroundColor Green
} else {
    Write-Host "[setup] WARN: could not parse status; copy supabase\... or set ini manually." -ForegroundColor Red
}

Write-Host ""
Write-Host "[setup] Done!  Studio: http://127.0.0.1:54323   API: http://127.0.0.1:54321" -ForegroundColor Green
Write-Host "[setup] Check tables in Studio (Table Editor): accounts / characters" -ForegroundColor Green
Write-Host "[setup] Stop: supabase\.bin\supabase.exe stop  (or db-stop.bat)" -ForegroundColor DarkGray
